# Spring boot application
spring:
  application:
    name: dubbo-provider
embedded:
  zookeeper:
     port: 2181
dubbo:
  scan:
    # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
    base-packages: com.ming.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
demo:
  service:
    version: 1.0.0